name: Quality Plugin Build & Test

on:
  push:
    paths:
      - gradle-quality-plugin/**
  pull_request:
    paths:
      - gradle-quality-plugin/**
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v5
        with:
          min-wrapper-count: 0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build, test, and lint
        working-directory: gradle-quality-plugin
        run: ./gradlew build test detekt ktlintCheck --no-daemon --stacktrace
