# Base action for registering octopus releases in the release-log
name: Register Release

on:
  workflow_call:
    inputs:
      octopus-module-name:
        required: true
        type: string
      release-version:
        required: true
        type: string

jobs:
  register-release-in-log:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Fetch release log
        run: |
          git clone ssh://git@bitbucket.spb.openwaygroup.com/f1/octopus-release-log.git release-log
          cd release-log
      - name: Register release
        run: |
          echo "Register release ${{ inputs.octopus-module-name }}-${{ inputs.release-version }}"
          if [[ ! -e ${{ inputs.octopus-module-name }}.txt ]]; then
	          touch ${{ inputs.octopus-module-name }}.txt
          fi
          echo "${{ inputs.release-version }}" | cat - ${{ inputs.octopus-module-name }}.txt > temp && mv temp ${{ inputs.octopus-module-name }}.txt
          git add ${{ inputs.octopus-module-name }}.txt
          git commit -m"${{ inputs.octopus-module-name }}-${{ inputs.release-version }}"
          git push
