# Base action for registering octopus releases in the release-log
name: Register Release

on:
  workflow_call:
    inputs:
      octopus-repository:
        type: string
        required: true
      release-version:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod
    env:
      OCTOPUS_MODULE_NAME: ''

    steps:
      - name: Launch action using REST
        run: |
          echo "OCTOPUS_MODULE_NAME=$(echo ${{ inputs.octopus-repository }} | cut -d'/' -f2)"
          echo 'var: ' $OCTOPUS_MODULE_NAME
          echo $OCTOPUS_MODULE_NAME >> "$GITHUB_ENV"
          echo 'env: ' ${{ env.OCTOPUS_MODULE_NAME }}
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.OCTOPUS_GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/octopusden/octopus-release-log/dispatches \
          -d '{ "event_type": "register-release", "client_payload": {"octopus-module-name": "${{ env.OCTOPUS_MODULE_NAME }}", "release-version": "${{ inputs.release-version }}"} }' \
          --fail
