# Base action for registering octopus releases in the release-log
name: Register Release

on:
  workflow_call:
    inputs:
      octopus-module-name:
        required: true
        type: string
      release-version:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  
jobs:
  register-release-in-log:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Fetch release log
        uses: actions/checkout@v4
        with:
          repository: octopusden/octopus-release-log
          path: release-log
          persist-credentials: false
          fetch-depth: 0

      - name: Register release
        run: |
          echo "Register release ${{ inputs.octopus-module-name }}-${{ inputs.release-version }}"
          cd release-log
          git pull
          git config user.name "gh-octopusden"
          git config user.email "gh-octopusden@gmail.com"
          git config --global core.autocrlf input
          # git config user.name github-actions
          # git config user.email github-actions@github.com
          ls -l
          if [[ ! -e ${{ inputs.octopus-module-name }}.txt ]]; then
            touch ${{ inputs.octopus-module-name }}.txt
          fi
          echo "${{ inputs.release-version }}" | cat - ${{ inputs.octopus-module-name }}.txt > temp && mv temp ${{ inputs.octopus-module-name }}.txt
          git diff
          git add ${{ inputs.octopus-module-name }}.txt
          git commit -m"${{ inputs.octopus-module-name }}-${{ inputs.release-version }}"
          git log
          git status
          git config --list
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.OCTOPUS_GITHUB_TOKEN }}
          repository: octopusden/octopus-release-log
          directory: release-log
