name: Check for artifact

on:
  workflow_call:
    inputs:
      artifact-pattern:
        required: true
        type: string
      prev_conclusion: 
        required: true
        type: string

jobs:
  check-http-artifact:
    runs-on: ubuntu-latest
    environment: Prod
    env:
      ATTEMPTS: 30
      BASE_URL: "https://repo1.maven.org/maven2/org/octopusden"

    steps:

      - name: Check Previous Workflow Outcome
        run: |
          if [ "${{ inputs.prev_conclusion }}" != "success" ]; then
            echo "Release workflow was unsuccessful, exiting..."
            exit 0     # ok
          fi
    
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get latest tag
        id: tag_version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          # check for version like this v222.444.0 or v1.0.34
          regex: '^v([0-9]|([1-9][0-9]*))\.([0-9]|([1-9][0-9]*))\.([0-9]|([1-9][0-9]*))$'

      # check artifact exists on nexus - synchronous implementation
      - name: Check Sonatype Nexus publish
        id: check-artifact
        run: |
          VERSION_FROM_TAG="${{ steps.tag_version.outputs.tag }}"      # v2.3.4
          VER="${VERSION_FROM_TAG#v}"                                  # 2.3.4
           
          PATTERN="${{ inputs.artifact-pattern }}"
          ART_PATH="${PATTERN//_VER_/${VER}}"
          
          ART_URL="${BASE_URL}/${ART_PATH}"
          echo "Current version is $VER"
          echo "Artifact url to check $ART_URL"

          for i in $(seq 1 $ATTEMPTS); do
            if curl -sSf "$ART_URL" -o artifact.jar; then
              echo "Artifact found!"
              exit 0
            else
              echo "Artifact not found at $ART_URL, retrying in 2 minutes..."
              sleep 120
            fi
          done
          exit 1
