# This is a basic release workflow for Octopus Java modules with publishing to Sonatype Nexus
name: Maven Release

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '8'
      increment-version-level:
        required: false
        type: string
        default: patch
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_TOKEN:
        required: true
      GPG_PASSPHRASE:
        required: true
      GPG_PRIVATE_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get latest tag
        id: tag_version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          regex: '^v([0-9]+)\..*'

      - name: Prepare new version
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump_semver
        with:
          current_version: ${{ steps.tag_version.outputs.tag }}
          level: ${{ inputs.increment-version-level }}

      - env:
          BUILD_VERSION: ${{ steps.bump_semver.outputs.new_version }}

      - run: |
          echo "BUILD_VERSION: ${{ env.BUILD_VERSION }}"

      - name: Set new version for maven
        # todo: use release version instead of master
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "org.codehaus.mojo:versions-maven-plugin:2.13.0:set -DnewVersion=${{ env.BUILD_VERSION }}"

      - name: Set up maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # gpg private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for gpg signing in deploy

      - name: Publish to Sonatype Nexus
        run: mvn --batch-mode deploy -P gpg
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Create Release
        # todo: use release version instead of master
        uses: "marvinpinto/action-automatic-releases@master"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "v${{ env.BUILD_VERSION }}"
          files: |
            pom.xml
