name: Check for artifact and register release in log

on:
  workflow_call:
    inputs:
      artifact-pattern:
        required: true
        type: string

jobs:
  check-http-artifact:
    runs-on: ubuntu-latest
    environment: Prod
    env:
      ATTEMPTS: 30
      BASE_URL: "https://repo1.maven.org/maven2/org/octopusden"
    outputs:
      release-version: ${{ steps.check-artifact.outputs.RELEASE_VERSION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get latest tag
        id: tag_version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          # check for version like this v222.444.0 or v1.0.34
          regex: '^v([0-9]|([1-9][0-9]*))\.([0-9]|([1-9][0-9]*))\.([0-9]|([1-9][0-9]*))$'

      # check artifact exists on nexus - synchronous implementation
      - name: Check Sonatype Nexus publish
        id: check-artifact
        run: |
          VERSION_FROM_TAG="${{ steps.tag_version.outputs.tag }}"         # v2.3.4
          VER=${VERSION_FROM_TAG#v}                                       # 2.3.4
          echo "RELEASE_VERSION=$VER" >> $GITHUB_OUTPUT

          PATTERN="${{ inputs.artifact-pattern }}"
          ART_PATH="${PATTERN//_VER_/$VER}"
          
          ART_URL="${BASE_URL}/${ART_PATH}"
          echo "Current version is $VER"
          echo "Artifact url to check $ART_URL"

          success=false

          for i in $(seq 1 $ATTEMPTS); do
            if curl -sSf "$ART_URL" -o artifact.jar; then
              echo "Artifact found!"
              success=true
              break
            else
              echo "Artifact not found at $ART_URL, retrying in 2 minutes..."
              sleep 120
            fi
          done

          if [ "$success" = false ]; then
            echo "All attempts failed. Exiting..."
            exit 1
          fi

  register-release-in-log:
    # register release in octopus-release-log
    needs: check-http-artifact
    if: ${{ success() }}
    uses: ./.github/workflows/common-register-release.yml
    name: Register release
    with:
      octopus-repository: ${{ github.repository }}
      release-version: ${{ needs.check-http-artifact.outputs.release-version }}
    secrets: inherit
