name: Check for artifact

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
      build-version:
        required: true
        type: string

jobs:
  check-http-artifact:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
    
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get latest tag
        id: tag_version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          regex: '^v([0-9]+)\..*'

      # check artifact exists on nexus - synchronous implementation
      - name: Check Sonatype Nexus publish
        id: check-artifact
        run: |
          VERSION_FROM_TAG="${{ steps.tag_version.outputs.tag }}"      # v2.3.4
          VER="${VERSION_FROM_TAG#v}"                                  # 2.3.4
          BASE_URL="https://repo1.maven.org/maven2/org/octopusden" 
          MODULE_NAME="${{ inputs.module-name }}"
          ART_URL="$BASE_URL/$MODULE_NAME/$VER/$MODULE_NAME-$VER.jar"
          echo "Current version is $VER"
          echo "Artifact url to check $ART_URL"
          
          for i in {1..30}; do
            if curl -sSf "$ART_URL" -o artifact.jar; then
              echo "Artifact found!"
              exit 0
            else
              echo "Artifact not found at $ART_URL, retrying in 2 minutes..."
              sleep 60
            fi
          done
          exit 1
