name: Check for artifact

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
      build-version:
        required: true
        type: string

jobs:
  check-http-artifact:
    runs-on: ubuntu-latest
    environment: Prod

    steps:

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      # check artifact exists on nexus - synchronous implementation
      - name: Check Sonatype Nexus publish
        id: check-artifact
        run: |
          VER="${{ steps.get-latest-tag.outputs.tag }}"
          BASE_URL="https://repo1.maven.org/maven2/org/octopusden" 
          MODULE_NAME="${{ inputs.module-name }}"
          ART_URL="$BASE_URL/$MODULE_NAME/$VER/$MODULE_NAME-$VER.jar"
          echo "Current version is $VER"
          echo "Artifact url to check $ART_URL"
          
          for i in {1..30}; do
            if curl -sSf "$ART_URL" -o artifact.jar; then
              echo "Artifact found!"
              break
            else
              echo "Artifact not found at $ART_URL, retrying in 2 minutes..."
              sleep 60
            fi
          done
        continue-on-error: true

      # check artifact exists on nexus - synchronous implementation
      - name: Determine Success
        run: exit $((! ${{ steps.check-artifact.outcome == 'success' }}))
