# This is a basic build workflow for Octopus Java modules published to Sonatype Central Repository
name: Snapshot Compile&UT

on:
  workflow_call:
    inputs:
      process_env:
        required: true
        type: string
      java-version:
        required: false
        type: string
        default: '8'
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: ${{ github.event.inputs.java-version }}
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}