# This is a basic release workflow for Octopus gradle Java modules with publishing to Sonatype Nexus and/or image registry
name: Gradle Release

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '8'
      docker-image:
        description: 'Publishing to docker registry'
        required: false
        type: boolean
        default: false
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_TOKEN:
        required: true
      GPG_PASSPHRASE:
        required: true
      GPG_PRIVATE_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod
    # todo: get rid of the next parameter
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest tag
        id: tag_version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          regex: '^v([0-9]+)\..*'

      - name: Prepare new version
        uses: actions-ecosystem/action-bump-semver@v1
        id: bump_semver
        with:
          current_version: ${{ steps.tag_version.outputs.tag }}
          level: ${{ inputs.increment-version-level }}

      - env:
          BUILD_VERSION: ${{ steps.bump_semver.outputs.new_version }}

      - run: |
          echo "BUILD_VERSION: ${{ env.BUILD_VERSION }}

      - name: Gradle build
        uses: octopus-base/common-java-gradle-build@gradle-templates
        with:
          java-version: ${{ inputs.java-version }}
          docker-image: ${{ inputs.docker-image }}
          build-version: ${{ env.BUILD_VERSION }}

      - name: Publish to Sonatype Nexus
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -Pversion=${{ env.BUILD_VERSION }}  -s
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSPHRASE }}

      - name: Log in to Docker Registry
        if: ${{ inputs.docker-image }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to docker registry
        if: ${{ inputs.docker-image }}
        run: docker push ghcr.io/${{ github.repository }}:${{ env.BUILD_VERSION }}

      - name: Create Release
        # todo: use fixed version instead of master
        uses: marvinpinto/action-automatic-releases@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: v${{ env.BUILD_VERSION }}
