# Base action for registering octopus releases in the release-log
name: Register Release

on:
  workflow_call:
    inputs:
      octopus-module-name:
        required: true
        type: string
      release-version:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  
jobs:
  register-release-in-log:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
#      - name: Fetch release log
#        uses: actions/checkout@v4
#        with:
#          repository: octopusden/octopus-release-log
#          path: release-log

      - name: Register release
        run: |
          echo "Register release ${{ inputs.octopus-module-name }}-${{ inputs.release-version }}"
          git pull https://gh-octopusden:${{ secrets.OCTOPUSDEN_PASSWORD}}@github.com/octopusden/octopus-release-log.git
          cd octopus-release-log
          git config user.name gh-octopusden
          git config user.email gh-octopusden@gmail.com
          ls -l
          if [[ ! -e ${{ inputs.octopus-module-name }}.txt ]]; then
            touch ${{ inputs.octopus-module-name }}.txt
          fi
          echo "${{ inputs.release-version }}" | cat - ${{ inputs.octopus-module-name }}.txt > temp && mv temp ${{ inputs.octopus-module-name }}.txt
          git add ${{ inputs.octopus-module-name }}.txt
          git commit -m"${{ inputs.octopus-module-name }}-${{ inputs.release-version }}"
          git push origin main
